// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: season.proto

package teams

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Season *int32 `protobuf:"varint,1,opt,name=season,proto3,oneof" json:"season,omitempty"`
}

func (x *SeasonRequest) Reset() {
	*x = SeasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_season_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonRequest) ProtoMessage() {}

func (x *SeasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_season_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonRequest.ProtoReflect.Descriptor instead.
func (*SeasonRequest) Descriptor() ([]byte, []int) {
	return file_season_proto_rawDescGZIP(), []int{0}
}

func (x *SeasonRequest) GetSeason() int32 {
	if x != nil && x.Season != nil {
		return *x.Season
	}
	return 0
}

type Season struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Season       int32  `protobuf:"varint,1,opt,name=season,proto3" json:"season,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active       bool   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt    string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DurationDays int32  `protobuf:"varint,5,opt,name=duration_days,json=durationDays,proto3" json:"duration_days,omitempty"`
}

func (x *Season) Reset() {
	*x = Season{}
	if protoimpl.UnsafeEnabled {
		mi := &file_season_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Season) ProtoMessage() {}

func (x *Season) ProtoReflect() protoreflect.Message {
	mi := &file_season_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Season.ProtoReflect.Descriptor instead.
func (*Season) Descriptor() ([]byte, []int) {
	return file_season_proto_rawDescGZIP(), []int{1}
}

func (x *Season) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *Season) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Season) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Season) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Season) GetDurationDays() int32 {
	if x != nil {
		return x.DurationDays
	}
	return 0
}

type SeasonRankingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seeason int32   `protobuf:"varint,1,opt,name=seeason,proto3" json:"seeason,omitempty"`
	Teams   []*Team `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
}

func (x *SeasonRankingResponse) Reset() {
	*x = SeasonRankingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_season_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeasonRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeasonRankingResponse) ProtoMessage() {}

func (x *SeasonRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_season_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeasonRankingResponse.ProtoReflect.Descriptor instead.
func (*SeasonRankingResponse) Descriptor() ([]byte, []int) {
	return file_season_proto_rawDescGZIP(), []int{2}
}

func (x *SeasonRankingResponse) GetSeeason() int32 {
	if x != nil {
		return x.Seeason
	}
	return 0
}

func (x *SeasonRankingResponse) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

var File_season_proto protoreflect.FileDescriptor

var file_season_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x74, 0x65, 0x61, 0x6d, 0x73, 0x1a, 0x0a, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42,
	0x09, 0x0a, 0x07, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x90, 0x01, 0x0a, 0x06, 0x53,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0c, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x79, 0x73, 0x22, 0x54, 0x0a,
	0x15, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x65, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x21, 0x0a, 0x05, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x52, 0x05, 0x74, 0x65,
	0x61, 0x6d, 0x73, 0x32, 0x8d, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x12, 0x14, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x73,
	0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x2e,
	0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x53, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x65, 0x64, 0x6d, 0x63, 0x6d, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2d, 0x67, 0x6f,
	0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_season_proto_rawDescOnce sync.Once
	file_season_proto_rawDescData = file_season_proto_rawDesc
)

func file_season_proto_rawDescGZIP() []byte {
	file_season_proto_rawDescOnce.Do(func() {
		file_season_proto_rawDescData = protoimpl.X.CompressGZIP(file_season_proto_rawDescData)
	})
	return file_season_proto_rawDescData
}

var file_season_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_season_proto_goTypes = []interface{}{
	(*SeasonRequest)(nil),         // 0: teams.SeasonRequest
	(*Season)(nil),                // 1: teams.Season
	(*SeasonRankingResponse)(nil), // 2: teams.SeasonRankingResponse
	(*Team)(nil),                  // 3: teams.Team
}
var file_season_proto_depIdxs = []int32{
	3, // 0: teams.SeasonRankingResponse.teams:type_name -> teams.Team
	0, // 1: teams.SeasonService.GetSeason:input_type -> teams.SeasonRequest
	0, // 2: teams.SeasonService.GetSeasonRanking:input_type -> teams.SeasonRequest
	1, // 3: teams.SeasonService.GetSeason:output_type -> teams.Season
	2, // 4: teams.SeasonService.GetSeasonRanking:output_type -> teams.SeasonRankingResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_season_proto_init() }
func file_season_proto_init() {
	if File_season_proto != nil {
		return
	}
	file_team_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_season_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_season_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Season); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_season_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeasonRankingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_season_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_season_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_season_proto_goTypes,
		DependencyIndexes: file_season_proto_depIdxs,
		MessageInfos:      file_season_proto_msgTypes,
	}.Build()
	File_season_proto = out.File
	file_season_proto_rawDesc = nil
	file_season_proto_goTypes = nil
	file_season_proto_depIdxs = nil
}
